Repository pesto-students/batch-9-Posto, pull requests merged in 2019-08, with the labels that each got.

#6 chore/Setup a mono-repo
  .gitignore
  client/.gitignore
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/serviceWorker.js
  package.json
  server/index.js
  server/package.json
Labels: setup

#7 setup: add a circleci config yml
  .circleci/config.yml
  server/package.json
Labels: setup

#9 chore/Setup server side Babel
  server/.babelrc
  server/.env
  server/package.json
Labels: setup

#10 setup/Add express template code
  server/app.js
  server/bin/www
  server/package.json
  server/public/stylesheets/style.css
  server/routes/index.js
  server/routes/users.js
  server/views/error.jade
  server/views/index.jade
  server/views/layout.jade
Labels: setup

#16 chore/Setup eslint and husky
  .eslintrc.json
  .prettierignore
  .prettierrc
  client/package.json
  client/src/App.jsx
  client/src/App.test.jsx
  client/src/index.js
  client/src/index.jsx
  client/src/serviceWorker.js
  package.json
  server/app.js
  server/index.js
  server/package.json
  server/public/stylesheets/style.css
  server/routes/index.js
  server/routes/users.js
Labels: setup

#17 Sumeetrohra/fix#13
  server/.env
Labels: Fix

#19 Fix/update gitignore
  .gitignore
Labels: Fix

#23 feat/Add Login layout to homescreen
  .eslintrc.json
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/index.css
  client/src/index.jsx
  client/src/logo.svg
  client/src/views/Login/index.jsx
Labels: enhancement

#28 chore/Setup a mono-repo
  .gitignore
  client/.gitignore
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/serviceWorker.js
  client/yarn.lock
  package.json
  server/index.js
  server/package.json
  server/yarn.lock
  yarn.lock
Labels: setup

#29 setup: add a circleci config yml
  .circleci/config.yml
  server/package.json
Labels: setup

#30 chore/Setup server side Babel
  server/.babelrc
  server/.env
  server/package.json
Labels: setup

#34 Setup: add express template code
  server/.babelrc
  server/.env
  server/app.js
  server/bin/www
  server/package.json
  server/routes/index.js
  server/routes/users.js
Labels: setup

#32 chore/Setup eslint and husky
  .eslintrc.json
  .prettierignore
  .prettierrc
  client/package.json
  client/src/App.jsx
  client/src/App.test.jsx
  client/src/index.jsx
  package.json
  server/app.js
  server/package.json
  server/public/stylesheets/style.css
  server/routes/index.js
  server/routes/users.js
Labels: setup

#33 feat/Add Login layout to homescreen
  .eslintrc.json
  client/package.json
  client/src/App.jsx
  client/src/components/CenterDiv/index.jsx
  client/src/components/EmailInput/index.jsx
  client/src/components/LoginForm/index.jsx
  client/src/components/PasswordInput/index.jsx
  client/src/components/Title/index.jsx
  client/src/elements/InputField/index.jsx
  client/src/index.css
  client/src/index.jsx
  client/src/views/Login/index.jsx
  server/package.json
Labels: enhancement

#41 fix/circle-ci client server test command fixes
  .circleci/config.yml
Labels: Fix

#37 fix/replace npm by yarn
  client/yarn.lock
  package.json
  server/yarn.lock
  yarn.lock
Labels: Fix

#35 fix/Remove .env
  .gitignore
  server/.env
Labels: Fix

#43 setup/Create pull_request_template.md
  .github/pull_request_template.md
Labels: setup

#46 feat/Add proptype validation to existing components
  client/package.json
  client/src/App.js
  client/src/App.jsx
  client/src/App.test.js
  client/src/components/CenterDiv/index.jsx
  client/src/components/EmailInput/index.jsx
  client/src/components/LoginForm/index.jsx
  client/src/components/PasswordInput/index.jsx
  client/src/components/Title/index.jsx
  client/src/elements/InputField/index.jsx
  client/src/index.js
  client/src/logo.svg
  client/src/serviceWorker.js
  client/src/views/Login/index.jsx
Labels: enhancement

#26 feat/Setup client-side routes
  client/package.json
  client/src/App.jsx
  client/src/App.test.jsx
  client/src/index.jsx
  client/yarn.lock
Labels: enhancement

#48 chore/Setup test for client
  client/package.json
  client/src/App.test.jsx
  client/src/setupTests.js
  client/src/views/Login/index.test.jsx
  client/yarn.lock
Labels: setup

#50 setup/mongodb connection and user route
  server/bin/www
  server/config.js
  server/controllers/users.js
  server/database/connection.js
  server/models/User.js
  server/package.json
  server/public/stylesheets/style.css
  server/routes/users.js
  server/yarn.lock
Labels: setup

#60 fix/Fix client build on netlify
  client/config-overrides.js
  client/package.json
  package.json
  yarn.lock
Labels: Fix

#63 setup/heroku deployment
  .circleci/config.yml
Labels: setup

#65 docs/Add contributing guidelines in readme.md
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation

#76 feature/Add Category Schema
  server/models/Category.js
Labels: sub-feature

#83 style/Add Posto logo
  README.md
  client/public/_redirect
  client/src/assets/posto.svg
  client/src/components/LoginForm/index.jsx
  client/src/components/SignupForm/index.jsx
  client/src/views/Login/index.jsx
  client/src/views/Signup/index.jsx
Labels: good first issue

#85 Navneet sahota/feat#55
  README.md
  client/package.json
  client/public/_redirects
  client/src/App.jsx
  client/src/Routes.jsx
  client/src/Routes.test.jsx
  client/src/components/Title/index.jsx
  client/src/elements/FormInput/index.jsx
  client/src/index.jsx
  client/src/views/NoMatch/NoMatch.module.css
  client/src/views/NoMatch/index.jsx
  package.json
  server/package.json
Labels: enhancement, test

#87 feat/ Posts Controller Methods
  .eslintrc.json
  server/.babelrc
  server/__tests__/controllers/posts.test.js
  server/__tests__/testUtils/addToDatabase.js
  server/__tests__/testUtils/testDbHelper.js
  server/config.js
  server/controllers/posts.js
  server/database/connection.js
  server/helpers/ObjectId.js
  server/models/User.js
  server/package.json
  server/routes/posts.js
  server/validations/joiOptions.js
  server/validations/posts.js
  yarn.lock
Labels: sub-feature

#84 feat/ Add signup, signin and auth middleware
  server/__tests__/auth.test.js
  server/config.js
  server/controllers/auth.js
  server/database/connection.js
  server/middleware/auth.js
  server/package.json
  server/routes/auth.js
  server/routes/index.js
  server/testUtils/testDbHelper.js
  server/utils.js
  server/yarn.lock
  yarn.lock
Labels: enhancement

#100 feat/ get categories list
  server/__tests__/controllers/categories.test.js
  server/__tests__/testUtils/addToDatabase.js
  server/controllers/categories.js
  server/routes/categories.js
Labels: sub-feature

#101 feat/Build header component
  client/src/Routes.jsx
  client/src/assets/avatar.png
  client/src/components/Header/index.jsx
  client/src/elements/CenterContainer/index.jsx
  client/src/elements/DropDown/index.jsx
  client/src/elements/HeaderMenu/index.jsx
  client/src/elements/HeaderMenuRight/index.jsx
  client/src/elements/ImageElement/index.jsx
  client/src/elements/MenuItem/index.jsx
  client/src/elements/SearchBox/index.jsx
  client/src/index.css
  client/src/views/HomePage/index.jsx
Labels: sub-feature

#103 fix/wrong name in MenuItem component
  client/src/Routes.jsx
  client/src/components/Header/index.jsx
  client/src/elements/CenterContainer/index.jsx
  client/src/elements/DropDown/index.jsx
  client/src/elements/HeaderMenu/index.jsx
  client/src/elements/HeaderMenuRight/index.jsx
  client/src/elements/MenuItem/index.jsx
  client/src/views/Home/index.jsx
Labels: Fix

#107 sub-feat/ search posts api
  server/__tests__/controllers/posts.test.js
  server/__tests__/testUtils/addToDatabase.js
  server/__tests__/testUtils/testDbHelper.js
  server/controllers/posts.js
  server/models/Post.js
  server/routes/posts.js
  server/validations/posts.js
Labels: sub-feature

#86 Navneet sahota/feat#81
  client/package.json
  client/src/API/index.js
  client/src/Routes.jsx
  client/src/Routes.test.jsx
  client/src/components/Markdown/Markdown.css
  client/src/components/Markdown/index.jsx
  client/src/components/PasswordInput/PasswordInput.test.jsx
  client/src/components/PostMenu/index.jsx
  client/src/components/PreviewPost/PreviewPost.module.css
  client/src/components/PreviewPost/index.jsx
  client/src/components/Title/index.jsx
  client/src/components/WritePost/WritePost.module.css
  client/src/components/WritePost/WritePost.test.jsx
  client/src/components/WritePost/index.jsx
  client/src/components/plugin/index.js
  client/src/components/plugin/plugins.js
  client/src/components/renderer/iframe.jsx
  client/src/components/renderer/index.js
  client/src/config/axiosConfig.js
  client/src/elements/CenterPost/index.jsx
  client/src/elements/MenuDropDown/index.jsx
  client/src/hooks/index.js
  client/src/hooks/useBoolean.js
  client/src/views/Login/Login.test.jsx
  client/src/views/Login/index.jsx
  client/src/views/New/New.test.jsx
  client/src/views/New/index.jsx
  client/src/views/Signup/index.jsx
  yarn.lock
Labels: sub-feature

#109 sub-feat/ get users api and tests
  server/__tests__/controllers/users.test.js
  server/controllers/users.js
Labels: api, sub-feature

#112 sub-feat/update user api
  server/__tests__/controllers/users.test.js
  server/controllers/users.js
  server/routes/users.js
  server/validations/users.js
Labels: api, sub-feature

#113 feat/Add Comment Schema
  server/models/Comment.js
Labels: sub-feature

#115 sub-feat/ profile pic upload api
  server/config.js
  server/controllers/users.js
  server/helpers/images.js
  server/package.json
  server/routes/users.js
  yarn.lock
Labels: api, sub-feature

#118 chore/ valid object id middleware
  server/__tests__/controllers/posts.test.js
  server/__tests__/controllers/users.test.js
  server/controllers/posts.js
  server/controllers/users.js
  server/middleware/validObjectId.js
  server/routes/posts.js
  server/routes/users.js
Labels: api, middleware

#121 feat/ Fetch user posts api
  server/__tests__/controllers/posts.test.js
  server/__tests__/testUtils/addToDatabase.js
  server/controllers/posts.js
Labels: api, sub-feature

#127 sub-feat/ forgot password api and template
  .eslintrc.json
  server/config.js
  server/controllers/auth.js
  server/helpers/mail.js
  server/helpers/tokenGenerator.js
  server/mailTemplates/forgot-password.pug
  server/models/User.js
  server/routes/auth.js
  server/validations/auth.js
  server/validations/mail.js
Labels: api, sub-feature

#129 sub-feat/ send welcome mail
  server/controllers/auth.js
  server/helpers/mail.js
  server/mailTemplates/forgot-password.pug
  server/mailTemplates/welcome.pug
Labels: sub-feature

#132 fix/Add user Id check in backend
  server/controllers/posts.js
Labels: Fix

#125 feat/Create Comment Controller methods
  server/__tests__/app.js
  server/__tests__/controllers/comments.test.js
  server/__tests__/testUtils/addToDatabase.js
  server/controllers/comments.js
  server/controllers/posts.js
  server/controllers/replies.js
  server/controllers/users.js
  server/routes/comments.js
  server/routes/replies.js
  server/validations/comments.js
  server/validations/replies.js
Labels: api, sub-feature

#133 sub-feat/ Reset password api
  server/controllers/auth.js
  server/models/User.js
  server/routes/auth.js
  server/validations/auth.js
Labels: api, sub-feature

#135 setup/ database seed generator
  server/models/Post.js
  server/package.json
  server/seedGenerator/categories.js
  server/seedGenerator/comments.js
  server/seedGenerator/index.js
  server/seedGenerator/populate.js
  server/seedGenerator/posts.js
  server/seedGenerator/users.js
  yarn.lock
Labels: database, setup, sub-feature

#136 feat/Build Homepage layout
  client/src/components/BlogCard/BlogCard.module.css
  client/src/components/BlogCard/index.jsx
  client/src/components/BlogDetails/index.jsx
  client/src/components/BlogList/index.jsx
  client/src/components/BlogList/index.test.jsx
  client/src/components/CategoryScrollBar/CategoryScrollBar.module.css
  client/src/components/CategoryScrollBar/index.jsx
  client/src/config/constants.js
  client/src/elements/HeaderMenu/index.jsx
  client/src/views/Home/index.jsx
Labels: enhancement

#138 fix/Make BlogList component reusable
  client/src/components/BlogList/index.jsx
  client/src/views/Home/index.jsx
Labels: Fix

#143 fix/ allow fetching posts by type alone
  server/controllers/posts.js
Labels: Fix, api

#145 sub-feat/ posts provide author and category details
  server/__tests__/controllers/posts.test.js
  server/controllers/posts.js
Labels: api

#146 fix/ get posts by categories
  server/controllers/posts.js
Labels: api

#148 fix/Fix home posts
  .gitignore
  client/src/components/BlogCard/index.jsx
  client/src/components/BlogDetails/index.jsx
  client/src/components/BlogList/index.jsx
  server/seedGenerator/posts.js
Labels: Fix

#150 feat/ top posts
  server/controllers/posts.js
  server/routes/posts.js
Labels: api

#155 fix/ populate author and category details
  server/controllers/posts.js
Labels: api

#156 Feat/HomePage and Posts By Categories
  client/src/components/BlogCard/index.jsx
  client/src/components/Header/index.jsx
  client/src/views/Category/index.jsx
  client/src/views/Home/index.jsx
Labels: feature

#158 Fix/Fix axios token error
  client/src/API/index.js
  client/src/components/CategoryScrollBar/index.jsx
  client/src/components/LoginForm/index.jsx
  client/src/components/SignupForm/index.jsx
  client/src/config/axiosConfig.js
  client/src/views/Category/index.jsx
  client/src/views/Home/index.jsx
Labels: Fix

#165 Fix/Error Handling in api calls
  client/src/API/index.js
  client/src/components/EditPost/index.jsx
  client/src/components/LoginForm/index.jsx
  client/src/components/SignupForm/index.jsx
  client/src/components/WritePost/index.jsx
  client/src/views/CreateAndEditPost/index.jsx
Labels: Fix

#166 feat/Search feature
  client/src/API/index.js
  client/src/Routes.jsx
  client/src/components/Header/index.jsx
  client/src/components/SearchBar/SearchBar.module.css
  client/src/components/SearchBar/index.jsx
  client/src/elements/SearchBox/index.jsx
  client/src/views/Search/index.jsx
  server/controllers/posts.js
Labels: feature

#167 feat/Add loader to each screen
  client/src/API/index.js
  client/src/components/Loader/Loader.module.css
  client/src/components/Loader/index.jsx
  client/src/views/Category/index.jsx
  client/src/views/CreateAndEditPost/index.jsx
  client/src/views/Home/index.jsx
Labels: enhancement

#171 fix/send profile pic url with user image
  server/utils.js
Labels: Fix

#173 feat/Implement Route based code splitting
  client/src/Routes.jsx
  client/src/components/BlogList/index.jsx
  client/src/components/CategoryScrollBar/index.jsx
  client/src/elements/LoaderCentered/LoaderCenter.jsx
Labels: enhancement

#175 feat/Add header to New and Edit Post
  client/src/components/Header/index.jsx
  client/src/components/Post/Post.module.css
  client/src/components/PostMenu/index.jsx
  client/src/elements/HeaderMenu/index.jsx
  client/src/views/CreateAndEditPost/index.jsx
Labels: enhancement

#177 feat/My posts page
  client/src/API/index.js
  client/src/Routes.jsx
  client/src/components/MyPostsMenu/index.jsx
  client/src/elements/MenuItem/index.jsx
  client/src/elements/PostMenu/index.jsx
  client/src/views/MyPosts/index.jsx
Labels: sub-feature

#88 feat/ view a post
  client/package.json
  client/src/API/index.js
  client/src/Routes.jsx
  client/src/components/Comment/index.jsx
  client/src/components/Comment/style.css
  client/src/components/CommentBox/index.jsx
  client/src/components/CommentsList/index.jsx
  client/src/components/PostAuthorDetails/index.jsx
  client/src/components/PostContent/index.jsx
  client/src/components/Reply/index.jsx
  client/src/components/ReplyBox/index.jsx
  client/src/components/ReplyList/index.jsx
  client/src/components/Upvotes/index.jsx
  client/src/components/UseAPI/index.jsx
  client/src/context/constants.js
  client/src/context/initialState.js
  client/src/context/reducer.js
  client/src/views/Post/index.jsx
  server/__tests__/controllers/comments.test.js
  server/controllers/comments.js
  server/controllers/posts.js
  server/controllers/replies.js
Labels: feature

#179 fix/ top posts sorting issue
  server/controllers/posts.js
Labels: Fix, api

#184 fix/ change creative director name
  server/mailTemplates/forgot-password.pug
  server/mailTemplates/welcome.pug
Labels: enhancement

#183 Fix/Markdown component when URL is incomplete/
  client/package.json
  client/src/components/Markdown/index.jsx
  client/src/components/Post/index.jsx
  client/src/components/plugin/index.js
  client/src/components/plugin/plugins.js
  yarn.lock
Labels: Fix

#187 fix/ send full profile pic url
  server/controllers/users.js
Labels: Fix, api

#189 feat/Add styles in Markdown component
  client/src/components/Markdown/Markdown.css
  client/src/components/Markdown/Markdown.module.css
  client/src/components/Markdown/index.jsx
  client/src/components/PreviewPost/PreviewPost.module.css
Labels: enhancement

#191 fix/ add view post links
  client/src/components/BlogCard/index.jsx
  client/src/components/Comment/index.jsx
  client/src/components/PostAuthorDetails/index.jsx
  client/src/components/Reply/index.jsx
Labels: Fix

#193 feat/Add navigation in Header dropdown
  client/src/components/Header/index.jsx
  client/src/elements/DropDown/index.jsx
  client/src/views/NoMatch/index.jsx
Labels: enhancement

#195 feat/Get image and description from markdown
  client/package.json
  client/src/components/BlogCard/index.jsx
  client/src/components/BlogList/index.jsx
  yarn.lock
Labels: enhancement

#196 feat/User profile page
  .eslintrc.json
  client/src/API/index.js
  client/src/Routes.jsx
  client/src/components/BlogCard/index.jsx
  client/src/views/Profile/index.jsx
Labels: sub-feature

#198 fix/fix eslintrc
  .eslintrc.json
Labels: Fix

#200 fix/New and Edit posts responsiveness
  client/src/components/Post/index.jsx
  client/src/components/PostMenu/PostMenu.module.css
  client/src/components/PostMenu/index.jsx
  client/src/elements/MenuDropDown/MenuDropDown.module.css
  client/src/elements/MenuDropDown/index.jsx
Labels: Fix

#202 feat/Add Markdown component to View Post
  client/src/components/PostContent/index.jsx
  client/src/views/Post/index.jsx
Labels: enhancement

#204 fix/Set active NavLink in CategoryScrollbar
  client/src/components/CategoryScrollBar/CategoryScrollBar.module.css
  client/src/components/CategoryScrollBar/index.jsx
  client/src/views/Category/index.jsx
Labels: Fix

#206 feat/ add pm2 functionality
  package.json
  server/__tests__/auth.test.js
  server/__tests__/controllers/categories.test.js
  server/__tests__/controllers/comments.test.js
  server/__tests__/controllers/posts.test.js
  server/__tests__/controllers/users.test.js
  server/__tests__/testUtils/addToDatabase.js
  server/ecosystem.config.js
  server/package.json
  server/src/app.js
  server/src/bin/www.js
  server/src/config.js
  server/src/controllers/auth.js
  server/src/controllers/categories.js
  server/src/controllers/comments.js
  server/src/controllers/posts.js
  server/src/controllers/replies.js
  server/src/controllers/users.js
  server/src/database/connection.js
  server/src/helpers/ObjectId.js
  server/src/helpers/images.js
  server/src/helpers/mail.js
  server/src/helpers/tokenGenerator.js
  server/src/middleware/auth.js
  server/src/middleware/validObjectId.js
  server/src/models/Category.js
  server/src/models/Comment.js
  server/src/models/Post.js
  server/src/models/User.js
  server/src/routes/auth.js
  server/src/routes/categories.js
  server/src/routes/comments.js
  server/src/routes/index.js
  server/src/routes/posts.js
  server/src/routes/replies.js
  server/src/routes/users.js
  server/src/utils.js
  server/src/validations/auth.js
  server/src/validations/comments.js
  server/src/validations/joiOptions.js
  server/src/validations/mail.js
  server/src/validations/posts.js
  server/src/validations/replies.js
  server/src/validations/users.js
  yarn.lock
Labels: enhancement, feature

#210 fix/New and Edit component data handling
  client/src/Routes.jsx
  client/src/components/BlogCard/index.jsx
  client/src/components/CategoryScrollBar/index.jsx
  client/src/components/CategoryScrollBar/index.test.jsx
  client/src/components/EditPost/index.jsx
  client/src/components/LoginForm/index.jsx
  client/src/components/Post/index.jsx
  client/src/components/PostMenu/index.jsx
  client/src/components/SignupForm/index.jsx
  client/src/components/Upvotes/index.jsx
  client/src/components/WritePost/index.jsx
  client/src/context/constants.js
  client/src/context/initialState.js
  client/src/context/reducer.js
  client/src/elements/MenuDropDown/index.jsx
  client/src/views/Category/index.jsx
  client/src/views/CreateAndEditPost/index.jsx
  client/src/views/Home/index.jsx
  client/src/views/MyPosts/index.jsx
  client/src/views/Post/index.jsx
  client/src/views/Profile/index.jsx
  client/src/views/Search/index.jsx
Labels: Fix

#212 feat/Add Help section
  client/src/components/Help/Help.module.css
  client/src/components/Help/index.jsx
  client/src/components/WritePost/index.jsx
  client/src/elements/MenuDropDown/MenuDropDown.module.css
  client/src/views/CreateAndEditPost/index.jsx
Labels: enhancement
