Repository pesto-students/batch-9-Posto, pull requests merged in 2019-09, with the labels that each got.

#215 feat/Add header and styles to View Posts
  client/src/components/Comment/index.jsx
  client/src/components/CommentBox/index.jsx
  client/src/components/Reply/index.jsx
  client/src/components/ReplyBox/index.jsx
  client/src/views/CreateAndEditPost/index.jsx
  client/src/views/Post/index.jsx
Labels: enhancement

#216 feat/Add theme font
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/postoSm.svg
  client/src/components/Markdown/index.jsx
  client/src/index.css
Labels: enhancement

#218 feat/Add basic styles to existing components
  client/src/components/BlogCard/BlogCard.module.css
  client/src/components/CommentBox/index.jsx
  client/src/components/ReplyBox/index.jsx
  client/src/index.css
  client/src/views/Category/index.jsx
  client/src/views/Home/index.jsx
  client/src/views/MyPosts/index.jsx
  client/src/views/Profile/index.jsx
  client/src/views/Search/index.jsx
Labels: enhancement

#219 feat/Image upload firebase
  client/.gitignore
  client/package.json
  client/src/API/index.js
  client/src/App.jsx
  client/src/firebaseConfig.js
  client/src/views/Profile/index.jsx
  server/src/validations/users.js
  yarn.lock
Labels: feature, sub-feature

#222 fix/getCategories call only when user is logged in
  client/src/Routes.jsx
Labels: Fix

#226 feat/Add favicon
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/public/postoSm.svg
Labels: enhancement

#228 feat/Delete post
  client/package.json
  client/src/API/index.js
  client/src/components/BlogCard/BlogCard.module.css
  client/src/components/BlogCard/index.jsx
  client/src/components/BlogList/index.jsx
  client/src/views/MyPosts/index.jsx
  yarn.lock
Labels: feature

#230 fix/ add authentication to routes and tests bypass token
  server/__tests__/controllers/categories.test.js
  server/__tests__/controllers/comments.test.js
  server/__tests__/controllers/posts.test.js
  server/__tests__/controllers/users.test.js
  server/src/config.js
  server/src/middleware/auth.js
  server/src/routes/index.js
  yarn.lock
Labels: api

#233 fix/ mailtemplates path
  client/src/API/index.js
  client/src/Routes.jsx
  server/src/helpers/mail.js
Labels: Fix

#234 feat/Redirect on save or publish
  client/src/components/WritePost/index.jsx
  client/src/views/Profile/index.jsx
Labels: Fix

#239 fix/Add token from context in API calls
  client/src/API/index.js
  client/src/Routes.jsx
  client/src/views/Home/index.jsx
Labels: Fix

#240 fix/Redirection on publish
  client/src/components/EditPost/index.jsx
  client/src/components/Post/index.jsx
  client/src/components/WritePost/index.jsx
  client/src/views/Profile/index.jsx
Labels: Fix

#242 fix/Login/Signup Button loading
  client/src/API/index.js
  client/src/Routes.jsx
  client/src/components/BlogCard/BlogCard.module.css
  client/src/components/BlogDetails/index.jsx
  client/src/components/LoginForm/index.jsx
  client/src/components/SignupForm/index.jsx
Labels: Fix

#244 feat/Use history.replace instead of default history.push
  client/src/components/Post/index.jsx
  client/src/elements/DropDown/index.jsx
  client/src/views/CreateAndEditPost/index.jsx
Labels: enhancement

#247 sub-feat/ generate fake mark down content
  client/package.json
  server/package.json
  server/seedGenerator/comments.js
  server/seedGenerator/config.js
  server/seedGenerator/index.js
  server/seedGenerator/populate.js
  server/seedGenerator/posts.js
  server/src/config.js
  server/src/controllers/users.js
  server/src/helpers/images.js
  server/src/routes/users.js
  yarn.lock
Labels: database

#246 feat/Add basic styles to app
  client/public/index.html
  client/src/components/Comment/index.jsx
  client/src/components/CommentBox/index.jsx
  client/src/components/Markdown/Markdown.module.css
  client/src/components/PostAuthorDetails/index.jsx
  client/src/components/Reply/index.jsx
  client/src/components/ReplyBox/index.jsx
  client/src/components/Upvotes/index.jsx
  client/src/elements/SearchBox/index.jsx
  client/src/index.css
  client/src/views/Post/index.jsx
Labels: enhancement

#250 feat/Add loader on login and signup screen
  client/src/App.jsx
Labels: enhancement

#252 feat/Add message box for login/signup error in place of alerts
  client/src/components/BlogList/index.jsx
  client/src/components/LoginForm/index.jsx
  client/src/components/SignupForm/index.jsx
Labels: enhancement

#254 fix/Fix CategoryPage and SearchPage crash onReload
  client/src/components/SearchBar/index.jsx
  client/src/views/Category/index.jsx
  client/src/views/Search/index.jsx
Labels: Fix

#256 fix/Redirection on draft post
  client/src/components/BlogCard/index.jsx
  client/src/components/BlogList/index.jsx
  client/src/views/MyPosts/index.jsx
  server/src/database/connection.js
Labels: Fix

#258 fix/Fix mongodb url
  server/src/database/connection.js
Labels: Fix
